version: '3.8'

services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    environment:
      FLASK_ENV: development
    networks:
      - app-network

  streamlit-app:
    build:
      context: ./streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-app:/app
    environment:
      STREAMLIT_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
